spring.application.name=copagolperu

# DATABASE config

spring.datasource.url=jdbc:postgresql://localhost:5432/copagolperu
spring.datasource.username=neillolazabal
spring.datasource.password=neill
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA config

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

application.security.jwt.secret-key=9a8b7c6d5e4f3g2h1i0j9k8l7m6n5o4p3q2r1s0t
application.security.jwt.expiration=120