spring.application.name=copagolperu

# DATABASE config
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT config
application.security.jwt.secret-key=${JWT_SECRET_KEY:9a8b7c6d5e4f3g2h1i0j9k8l7m6n5o4p3q2r1s0t}
application.security.jwt.expiration=${JWT_EXPIRATION:120}